#!/usr/bin/env python

from __future__ import print_function

import argparse
import os
import sys
from errno import EEXIST

import jinja2
from jinja2 import Environment, FileSystemLoader


def destination_fname(fname):
    r = fname
    if fname.endswith(".jinja"):
        r = fname.strip(".jinja")
    return r


def write(s, target):
    print("Writing \"%s\"... " % os.path.realpath(target), file=sys.stderr, end='')

    try:
        os.makedirs(os.path.dirname(target))
    except OSError as e:
        if e.errno == EEXIST: pass
        else: raise

    open(target, 'w').write(s)

    print("Done!", file=sys.stderr)

parser = argparse.ArgumentParser(description="Process jinja2 templates")
parser.add_argument("files", metavar="FILE", type=str, nargs="+")
parser.add_argument("--template-search-path", "-s", metavar="PATH", action="append")
parser.add_argument("--dest", "-d", default=".")

if __name__ == "__main__":
    args = parser.parse_args()

    files = args.files
    search_path = args.template_search_path or ["."]
    destination = args.dest

    env = Environment(loader=FileSystemLoader(search_path))

    for fname in files:
        template = env.get_template(fname)
        target = os.path.join(destination, destination_fname(fname))
        if os.path.realpath(template.filename) == os.path.realpath(target):
            print("ERROR: source \"%s\" and target \"%s\" are the same!" % (fname, target), file=sys.stderr)
        else:
            s = template.render()
            write(s, target)
