#!/usr/bin/env python

import argparse
import os

import jinja2
from jinja2 import Environment, FileSystemLoader


def destination_fname(fname):
    r = fname
    if fname.endswith(".jinja"):
        r = fname.strip(".jinja")
    return r


parser = argparse.ArgumentParser(description="Process jinja2 templates")
parser.add_argument("files", metavar="F", type=str, nargs="+")
parser.add_argument("--template-search-path", "-s", metavar="T", type=str, action="append")
parser.add_argument("--dest", "-d", metavar="D", type=str, action="store", default=".")

if __name__ == "__main__":
    args = parser.parse_args()

    files = args.files
    search_path = args.template_search_path or ["."]
    destination = args.dest

    env = Environment(loader=FileSystemLoader(search_path))

    for fname in files:
        template = env.get_template(fname)
        target = os.path.join(destination, destination_fname(fname))
        if os.path.realpath(template.filename) == os.path.realpath(target):
            print "ERROR: source \"%s\" and target \"%s\" are the same!" % (fname, target)
        else:
            print "Writing \"%s\"..." % os.path.realpath(target),
            s = template.render()
            open(target, 'w').write(s)
            print "Done!"
