#!/usr/bin/env python

import argparse

import jinja2
from jinja2 import Environment, FileSystemLoader


def destination_fname(fname):
    r = fname
    if fname.endswith(".jinja"):
        r = fname.strip(".jinja")
    return r


parser = argparse.ArgumentParser(description="Process jinja2 templates")
parser.add_argument("files", metavar="F", type=str, nargs="+")
parser.add_argument("--template-search-path", "-s", metavar="T", type=str, action="append")

if __name__ == "__main__":
    args = parser.parse_args()

    files = args.files
    search_path = args.template_search_path

    env = Environment(loader=FileSystemLoader(search_path))

    for fname in files:
        template = env.get_template(fname)
        print template.render()
